/* Generated By:JavaCC: Do not edit this line. ConverterConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConverterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 4;
  /** RegularExpression Id. */
  int QUOTE = 5;
  /** RegularExpression Id. */
  int ADD = 6;
  /** RegularExpression Id. */
  int WITH = 7;
  /** RegularExpression Id. */
  int WITHLINK = 8;
  /** RegularExpression Id. */
  int WITHTEXT = 9;
  /** RegularExpression Id. */
  int WITHSOURCE = 10;
  /** RegularExpression Id. */
  int WITHCOLOR = 11;
  /** RegularExpression Id. */
  int WITHFONT = 12;
  /** RegularExpression Id. */
  int TEXT = 13;
  /** RegularExpression Id. */
  int COLOR = 14;
  /** RegularExpression Id. */
  int FONT = 15;
  /** RegularExpression Id. */
  int LINK = 16;
  /** RegularExpression Id. */
  int PARA = 17;
  /** RegularExpression Id. */
  int HEAD = 18;
  /** RegularExpression Id. */
  int IMAGE = 19;
  /** RegularExpression Id. */
  int SOURCE = 20;
  /** RegularExpression Id. */
  int NULL = 21;
  /** RegularExpression Id. */
  int AND = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<ALPHANUMERIC>",
    "\"\\\"\"",
    "\"add\"",
    "\"with\"",
    "<WITHLINK>",
    "<WITHTEXT>",
    "<WITHSOURCE>",
    "<WITHCOLOR>",
    "<WITHFONT>",
    "\"text\"",
    "\"color\"",
    "\"font\"",
    "\"link\"",
    "\"paragraph\"",
    "\"heading\"",
    "\"image\"",
    "\"source\"",
    "\"\"",
    "\"and\"",
  };

}
